name: heapo_env
channels:
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.8.*
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pylint=2.16.2
  - notebook=6.5.4
  - tqdm=4.65.0
  - pip:
    - python-dateutil
